apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-1-deployment
  namespace: performance-testing
  labels:
    app: worker-1 #this label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-1 #this label
  template:
    metadata:
      labels:
        app: worker-1 #this label
        label: worker
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: worker-1
        image: localhost:32000/worker-release:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: redis_host
        - name: MASTER_IP
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: master_ip
        - name: WORKER_NAME
          value: worker-1-service:5000
        volumeMounts:
        - mountPath: "/home/Backend/Performance-Testing-Data"
          name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: worker-1-service
  namespace: performance-testing
  labels:
    app: worker-1-service
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: worker-1 #this label
  sessionAffinity: None
